// examples/vue-demo/src/App.vue
<template>
  <div class="app">
    <h1>Icon Forge Vue Demo</h1>

    <div class="icons">
      <ArrowRight :size="24" />
      <ArrowRight :size="32" color="blue" />
      <ArrowRight :size="48" color="red" :stroke-width="3" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ArrowRight } from '@dawnice/icon-forge-vue/icons';
</script>

<style scoped>
.app {
  padding: 50px;
}

.icons {
  display: flex;
  gap: 20px;
  margin-top: 30px;
}
</style>

// examples/svelte-demo/src/App.svelte
<script lang="ts">
  import ArrowRight from '@dawnice/icon-forge-svelte/icons/ArrowRight.svelte';
</script>

<main>
  <h1>Icon Forge Svelte Demo</h1>

  <div class="icons">
    <ArrowRight size={24} />
    <ArrowRight size={32} color="blue" />
    <ArrowRight size={48} color="red" strokeWidth={3} />
  </div>
</main>

<style>
  main {
    padding: 50px;
  }

  .icons {
    display: flex;
    gap: 20px;
    margin-top: 30px;
  }
</style>
